cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'homebrew/services'

brew 'vim'
brew 'emacs'
brew 'tmux'
brew 'git'
brew 'python3'
brew 'sass/sass/sass'
brew 'ispell'
brew 'npm'

cask 'spacemacs'
cask 'visual-studio-code'
cask 'firefox-nightly'
cask 'vlc'
cask 'dropbox'
cask 'docker'
cask 'keepassxc'
cask 'blender'
cask 'gimp'
cask 'karabiner-elements'
cask 'slate'
cask 'unity-hub'
cask 'obs'
cask 'twine'
cask 'slack'
cask 'inkscape'
cask 'krita'
cask 'steam'
